### ISSUE TITLE
Question about uploading a file.

### ISSUE THREAD

**Issue by JordanMajd** [gseguin/NanoHTTPd#1]
Whenever you upload a file via nanoHTTPD a name is assigned to it, by default this is a string of random numbers, but you can change it to whatever you want in the source code. However, I want the file to maintain its original filename,  I don't know how to get this data from the HTML POST method into a string. Any advice is welcomed.

**Comment by gseguin** [comment]
@lordbunson, the purpose of nanoHTTPd is mostly to serve a directory not implement a full on HTTP server. Feel free to submit a pull request or fork it.

**Comment by JordanMajd** [comment]
Hey, thanks for the advice. I dropped the project I was working on because of some changes added with Android 3.2. However,  back then I was a terrible programmer, while still not great I am finally competent.  I might look into forking it and adding an upload function where you have the ability to maintain the original file name. Thanks for the suggestion. While I wouldn't expect anyone to use it, it will be a fantastic learning experience.

**Comment by gseguin** [comment]
Closed #1
